### ISSUE TITLE
Installation pains and blocks

### ISSUE THREAD

**Issue by danshumaker** [matejak/argbash#34] opened 2018-02-02 16:48 UTC
Hi,
Just letting you know of some installation pains and some blockers.

mac OSX High Sierra + homebrew and the latest commit: a585507a2e1b215dca7f13ea7b2626e06655e6bb

running "sudo make install PREFIX=/usr" as example says caused a mkdir -p ///usr/bin to be executed.  So inside the Make file I see that ROOT is set to / already so no need to include a slash between the $(ROOT)/$(PREFIX),  furthermore "sudo make install PREFIX=usr" caused a permission denied error because that dir has some acl's on it.  This did the trick though 

"sudo make install PREFIX=usr/local"

Then after running arbash-init to create my template and attempting to "feed it back to argbash" I also get permission denied as follows:

```BASH
BASHdan@ShuPro /Users/dan/bin/bash >>argbash rebuild.atmpl
cat: /usr/local/lib/argbash/argbash-lib.m4: Permission denied
cat: /usr/local/lib/argbash/output.m4: Permission denied

Error during autom4te run, aborting!

BASHdan@ShuPro /Users/dan/bin/bash >>sudo chmod -R 755 /usr/local/bin/argbash*
BASHdan@ShuPro /Users/dan/bin/bash >>argbash rebuild.atmpl
cat: /usr/local/lib/argbash/argbash-lib.m4: Permission denied
cat: /usr/local/lib/argbash/output.m4: Permission denied

Error during autom4te run, aborting!

BASHdan@ShuPro /Users/dan/bin/bash >>sudo chmod -R 755 /usr/local/lib/arg*
BASHdan@ShuPro /Users/dan/bin/bash >>argbash rebuild.atmpl
/


dan@ShuPro /Users/dan/bin/bash >>argbash rebuild.atmpl
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/m4:stdin:11: cannot open `collectors.m4': No such file or directory
autom4te: /usr/bin/m4 failed with exit status: 1
Error during autom4te run, aborting!
```
I wasnt' sure if autoconf was installed so checked that:
```
BASHdan@ShuPro /Users/dan/bin/bash >>brew install autoconf
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 3 taps (homebrew/core, homebrew/php, caskroom/cask).
==> New Formulae
gocryptfs
==> Updated Formulae
homebrew/php/composer ✔            app-engine-java                    docfx                              faas-cli                           git-imerge                         hubflow                            pandoc-citeproc                    snapcraft                          stockfish
abnfgen                            coffeescript                       emscripten                         fn                                 grpc                               libmicrohttpd                      quantlib                           sourcekitten                       swiftformat
amber                              diamond                            etcd                               gammaray                           heroku                             mercurial                          snakemake                          sslyze

Warning: autoconf 2.69 is already installed
```

So I think all my permissions are straightened out but my system doesn't seem to have the "collectors.m4" file.. Whatever that is.  Is it a missing library.

#blocked.

**Comment by matejak** [comment] 2018-02-04 11:29
Hello, thank you for your time that you took to report the issue!
I will address sub-issues point by point:

1. `sudo make install PREFIX=/<whatever>` is still the recommended way how to install the software. The consecutive slashes s.a. `mkdir -p ///<whatever>/bin` are harmless. The Makefile is somehow more complicated inside in order to make it easy for package maintainers to package Argbash. So this is not an issue.
2. Indeed, the `/usr` directory is usually writable only by `root`. You chose a different location and installation worked for you. This is also not an issue.
3. Some files were not readable (or even accessible) - those were the "Permission denied" errors. You have solved them using `chmod`, but I see that a more straightforward error message would be much better for you.
4. The `collectors.m4` file was missing from the Argbash package. I have fixed the tests so this is detected and I have also fixed this issue in the current master.

**Comment by matejak** [comment] 2018-02-05 21:58
The point 3 has also been addressed in the master branch, so I will close this issue. Please reopen it if you still perceive rough edges!

**Comment by danshumaker** [comment] 2018-02-06 00:17
I couldn't get it to work with the new commit, but I'll keep trying, time permitting.

**Comment by matejak** [comment] 2018-03-11 12:55
As you have not provided feedback and I believe that the issue is resolved, I close it. However, don't hesitate to reopen it if you disagree.

**Closed by matejak** 2018-03-11 12:55 UTC
