### ISSUE TITLE
Required named arguments?

### ISSUE THREAD

**Issue by gdevenyi** [matejak/argbash#64] opened 2019-01-30 20:40 UTC
I don't see in the API a way to define a required named argument. If that is indeed not the case, I would like to request such an option.

Thanks!

**Comment by matejak** [comment] 2019-01-31 08:49
This is a duplicate of #56.
You can implement the "required" part in your code, i.e. if the respective value is empty, raise an error. However, this functionality would violate POSIX/GNU command-line interface standards.

**Closed by matejak** 2019-01-31 08:49 UTC

**Comment by gdevenyi** [comment] 2019-01-31 14:08
Ah, I wasn't aware of that violating the command-line standards, I'd rather maintain those. Thanks.
